hash-format = "sha256"

[[files]]
file = "config/fancymenu/assets/button.png"
hash = "3d09cc47bc50969360864e332645fbc761a5b98d6acbe77056d67089d63a03ef"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"
hash = "ff492043eaf454c46e949d5eef32ece90cc5a19feb50a161dd29a43b5732c880"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "6f839fad9a09709e9c2d1b269218da6a515ea31495575de5bdbc901147740327"

[[files]]
file = "config/fancymenu/customization/title_screen_layout.txt"
hash = "52dc90a3dc548ece2a4f7c18b92e1bd0e26ed4b56f6e780a01f8f67389d5875b"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"
hash = "051d700ea7ff1bd626063d60f9a9cd65a0af1fed5903706d1e70fce20bcb2495"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"
hash = "9a25d3dc708e43eabafce5479a13c02dae15bc7f673afb2745b8b2ba48a97dc0"

[[files]]
file = "config/fancymenu/options.txt"
hash = "5f9ff772228135fe6d8e56c5ece5a7bbacd04f1c46d489b92a14034ccbe59798"

[[files]]
file = "config/fancymenu/ui_themes/dark.json"
hash = "3f1263eaf693fdb6a315099b06797ac18830faa66c620916a80337a5082fd850"

[[files]]
file = "config/fancymenu/ui_themes/light.json"
hash = "3fcfc5f9957fbb86aea846c9ad49a24f47ca709c523c4018b584668e38b72f41"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "3d7d4cda73d6bde134a568ccbe4e8d2e7fbe701570012b71fa45acdb2258c823"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "51ce40d61d14d9f5e2f678c31b59d45a433870ad62702606fa1ef08ee0d6d1e5"

[[files]]
file = "config/mutils/mutils.json5"
hash = "757de8bccbbe97eb5d8e4ba6990880b52cb71b066fad1c7b2e25cfe79bef44ed"

[[files]]
file = "config/sodium-extra-options.json"
hash = "758951a47a3c1b2057c92159cea555b105f0d5f589fc850758e8348305512a50"

[[files]]
file = "icon.png"
hash = "b2eeba11d5ff5d6c32bc8d6e1eb6f3268e6e08e1240122d1c7dd918ed71f7f6f"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a8f073ab0640d9e501fe3fc95d282306000fd6eab3186fd682269c0d0913b307"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "eaa52d6ff1bcb539956d50626085d9185eca346fabcf6b3c176c53192b9958ec"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "a5f67311e64ea67e8097c1fdd4d20cf11e1c5236334b5becabad7dabdae975db"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "281dfa2e0e51ce16433e31d1ba6e1db9fe2fd038bfeecd05a643c294163a4cb3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "276947b1f9933ca2220a00736aba177e4034ca9a45cad9f258abf762fdb3bb0b"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "2c8f1f08da355faa45fd5215a1187af1a6250dacf41eaaf80786055216a87caf"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "e379dcd9dfc17994be22c8ebd94ddb3e61c5e8498ba9a4f3e79b4e07ae253b43"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "9ba08ebdb00a63de04192fc17a58ae464fbd477c97e678e9c01ab3ac15eebd0e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/mutils.pw.toml"
hash = "59c8bfd174e912ad557a71b91cf21e7f8bcec9ec93be30218549643c14436f44"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "b13be55b8550c635f36740dc65a751e6e1154de25319470e70cc2fbf18fd5ff9"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "ab6def9d98d3f5bf12f78845bdb770a19d5ca590c571e60184e537ffa14dcbee"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "986e43ff06d2a79effec6e219aca063d7b53a98096c5f63983f23cf54c11c7e5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "5e87caea13a44193abf997de56cf3cab2eb9feb1d8be35e0203f06df3552b9c5"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "9ce3767540efbf35e0a0c266040c9879efc9136ec59cd38e06e45b3c3c3e90e0"
metafile = true

[[files]]
file = "mods/wi-zoom.pw.toml"
hash = "d2d887d505b3f5352c2469408e993880e302f458f743204f0540c4f10794ca39"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1113d43c39a9866252a83ee50d16aa3ce6fcf749acd84d58b05ca09eba4d187b"
metafile = true

[[files]]
file = "options.txt"
hash = "22bc36590627f9f04d493e53aa593b4b814ba32d5323a51c3c39076163f20096"

[[files]]
file = "resourcepacks/OptiArk Resources/assets/minecraft/textures/gui/title/edition.png"
hash = "0459161175b3dbd84c42d8a9c3b35fb6bfbc764b4475ab9d1d31e81a514f3db6"

[[files]]
file = "resourcepacks/OptiArk Resources/assets/minecraft/textures/gui/title/minecraft.png"
hash = "9bdc5c88cf9d684eb73c27de55bdc7c9940126e7b6a7e2c7e53554209d15147f"

[[files]]
file = "resourcepacks/OptiArk Resources/pack.mcmeta"
hash = "42c0c3db72f7303b589ff4dfdbc0e4ef59439b0bcf512afe6c9358e75bb400b1"

[[files]]
file = "resourcepacks/OptiArk Resources/pack.png"
hash = "b2eeba11d5ff5d6c32bc8d6e1eb6f3268e6e08e1240122d1c7dd918ed71f7f6f"
