name = "OptiArk"
author = "ark"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ef806f9b6dd2386a67b908373d82bc9ab75d9a639821b137189ab40e1f0ff29"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
