name = "OptiArk-Nvidium"
author = "ark"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6823402e872091cb9e7b3ff7a572d6d059901c1622ecd4cad48e402ab2347041"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
