name = "OptiArk-Vulkan"
author = "ark"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f7767f67182de17aeb0a18430aafd2bf0273552ae68e1ab50aa6bfeb5b852fd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
